CREATE TABLE [dbo].[tblBuyNetEntry] (
    [BuyNetEntryID]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [RecordLocator]       BIGINT          NOT NULL,
    [RowLoadedDateTime]   DATETIME2 (7)   CONSTRAINT [DF_tblBuyNetEntry_RowLoadedDateTime] DEFAULT (sysdatetime()) NOT NULL,
    [RowUpdatedDateTime]  DATETIME2 (7)   NULL,
    [LastChangedByEmpID]  VARCHAR (128)   NULL,
    [VIN]                 VARCHAR (17)    NULL,
    [Year]                SMALLINT        NULL,
    [Make]                VARCHAR (100)   NULL,
    [Model]               VARCHAR (100)   NULL,
    [Mileage]             INT             NULL,
    [Size]                VARCHAR (50)    NULL,
    [BuyerName]           VARCHAR (100)   NULL,
    [BuyerEmpID]          VARCHAR (128)   NULL,
    [SourcingRegion]      VARCHAR (50)    NULL,
    [CRLLT]               INT             NULL,
    [PurchaseDate]        DATE            NULL,
    [AuctionHouse]        VARCHAR (200)   NULL,
    [AuctionName]         VARCHAR (200)   NULL,
    [BidTypeKey]          VARCHAR (50)    NULL,
    [PurchaseChannel]     VARCHAR (50)    NULL,
    [IsPreviousDTVehicle] BIT             CONSTRAINT [DF_tblBuyNetEntry_IsPreviousDTVehicle] DEFAULT ((0)) NOT NULL,
    [SellerName]          VARCHAR (200)   NULL,
    [BaseCost]            DECIMAL (10, 4) NULL,
    [BuyerFee]            DECIMAL (10, 4) NULL,
    [OtherFee]            DECIMAL (10, 4) NULL,
    [IsIfBid]             TINYINT         CONSTRAINT [DF_tblBuyNetEntry_IsIfBid] DEFAULT ((0)) NOT NULL,
    [IsDeleted]           TINYINT         CONSTRAINT [DF_tblBuyNetEntry_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_tblBuyNetEntry_BuyNetEntryID] PRIMARY KEY CLUSTERED ([BuyNetEntryID] ASC) WITH (FILLFACTOR = 90)
);

