CREATE TABLE [dbo].[tblListing] (
    [ListingId]             BIGINT        IDENTITY (1, 1) NOT NULL,
    [ListingHeading]        VARCHAR (MAX) NULL,
    [ListingType]           VARCHAR (MAX) NULL,
    [ListingUrl]            VARCHAR (MAX) NULL,
    [ListingFirstDate]      VARCHAR (MAX) NULL,
    [DaysOnMarket]          BIGINT        NULL,
    [DealerName]            VARCHAR (MAX) NULL,
    [DealerStreet]          VARCHAR (MAX) NULL,
    [DealerCity]            VARCHAR (MAX) NULL,
    [DealerState]           VARCHAR (MAX) NULL,
    [DealerZipcode]         BIGINT        NULL,
    [DealerUrl]             VARCHAR (MAX) NULL,
    [DealerEmail]           VARCHAR (MAX) NULL,
    [DealerPhone]           VARCHAR (MAX) NULL,
    [DealerType]            VARCHAR (MAX) NULL,
    [StockType]             VARCHAR (MAX) NULL,
    [Vin]                   VARCHAR (MAX) NULL,
    [Uvc]                   BIGINT        NULL,
    [Mileage]               BIGINT        NULL,
    [Price]                 BIGINT        NULL,
    [Msrp]                  BIGINT        NULL,
    [ModelYear]             BIGINT        NULL,
    [Make]                  VARCHAR (MAX) NULL,
    [Model]                 VARCHAR (MAX) NULL,
    [Series]                VARCHAR (MAX) NULL,
    [Style]                 VARCHAR (MAX) NULL,
    [Certified]             INT           NULL,
    [HasLeather]            INT           NULL,
    [HasNavigation]         INT           NULL,
    [ExteriorColor]         VARCHAR (MAX) NULL,
    [ExteriorColorCategory] VARCHAR (MAX) NULL,
    [InteriorColor]         VARCHAR (MAX) NULL,
    [InteriorColorCategory] VARCHAR (MAX) NULL,
    [PriceAnalysis]         INT           NULL,
    [WheelbaseFromVin]      VARCHAR (MAX) NULL,
    [DrivetrainFromVin]     VARCHAR (MAX) NULL,
    [EngineFromVin]         VARCHAR (MAX) NULL,
    [TransmissionFromVin]   VARCHAR (MAX) NULL,
    [FuelTypeFromVin]       VARCHAR (MAX) NULL,
    [OptionalFeatures]      VARCHAR (MAX) NULL,
    [StandardFeatures]      VARCHAR (MAX) NULL,
    [SellerNotes]           VARCHAR (MAX) NULL,
    [NumberPriceChanges]    BIGINT        NULL,
    [PriceHistoryDelimited] VARCHAR (MAX) NULL,
    [DistanceToDealer]      FLOAT (53)    NULL,
    [VehicleAnalyticDataID] BIGINT        NULL,
    CONSTRAINT [PK_tblListing_ListingID] PRIMARY KEY CLUSTERED ([ListingId] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_tblVehicleAnalyticData_VehicleAnalyticDataID] FOREIGN KEY ([VehicleAnalyticDataID]) REFERENCES [dbo].[tblVehicleAnalyticData] ([VehicleAnalyticDataID])
);

