CREATE TABLE [dbo].[tblStock] (
    [AcquisitionDate]                   DATETIME        NULL,
    [AcquisitionCostCenterID]           INT             NULL,
    [AcquisitionType]                   VARCHAR (2)     NULL,
    [ActualWriteDownDate]               DATETIME        NULL,
    [ActualDatePurchased]               DATETIME        NULL,
    [BaseCost]                          DECIMAL (15, 4) NULL,
    [LastUpdateDate]                    DATETIME        NULL,
    [BuyerID]                           INT             NULL,
    [Color1]                            VARCHAR (50)    NULL,
    [Color2]                            VARCHAR (50)    NULL,
    [ColorID]                           INT             NULL,
    [CurrentCostCenterID]               INT             NULL,
    [ClassRepairCost]                   DECIMAL (15, 4) NULL,
    [DaysAtReadyline]                   INT             NULL,
    [DaysAtWIP]                         INT             NULL,
    [DaysinLotRepair]                   INT             NULL,
    [DaysInTransit]                     INT             NULL,
    [DealerDate]                        DATETIME        NULL,
    [DealerCostCenterID]                INT             NULL,
    [EstimatedShipDays]                 SMALLINT        NULL,
    [VIN]                               VARCHAR (17)    NULL,
    [KickDate]                          DATETIME        NULL,
    [LotAge]                            INT             NULL,
    [ClassMake]                         VARCHAR (50)    NULL,
    [RoundedMileage]                    INT             NULL,
    [MileageID]                         INT             NULL,
    [MMRAcquisitionAuctionAveragePrice] DECIMAL (15, 4) NULL,
    [MMRAcquisitionAuctionCleanPrice]   DECIMAL (15, 4) NULL,
    [MMRAcquisitionRetailAveragePrice]  DECIMAL (15, 4) NULL,
    [MMRAcquisitonRetailCleanPrice]     DECIMAL (15, 4) NULL,
    [MMRCurrentAuctionAveragePrice]     DECIMAL (15, 4) NULL,
    [MMRCurrentAuctionCleanPrice]       DECIMAL (15, 4) NULL,
    [MMRCurrentRetailAveragePrice]      DECIMAL (15, 4) NULL,
    [MMRCurrentRetailCleanPrice]        DECIMAL (15, 4) NULL,
    [ClassModel]                        VARCHAR (50)    NULL,
    [NetSaleDate]                       DATETIME        NULL,
    [Odometer]                          INT             NULL,
    [OriginalStockNumber]               BIGINT          NULL,
    [OriginalWriteDownDate]             DATETIME        NULL,
    [PmtTypID]                          INT             NULL,
    [ProductTypeID]                     INT             NULL,
    [ProductionDate]                    DATETIME        NULL,
    [ProductType]                       VARCHAR (5)     NULL,
    [ReadyLineCostCenterID]             INT             NULL,
    [ReceiptDate]                       DATETIME        NULL,
    [ReceiptCostCenterID]               INT             NULL,
    [ClassStyle]                        VARCHAR (50)    NULL,
    [StatusCode]                        VARCHAR (2)     NULL,
    [AuctionBuyFee]                     DECIMAL (15, 4) NULL,
    [StockNumber]                       BIGINT          NOT NULL,
    [StockOwner]                        INT             NULL,
    [Transmission]                      VARCHAR (8)     NULL,
    [ClassTotalCost]                    DECIMAL (15, 4) NULL,
    [TotalWriteDowns]                   DECIMAL (15, 4) NULL,
    [AuctionTransportVendorID]          VARCHAR (6)     NULL,
    [TrueRepairCost]                    DECIMAL (15, 4) NULL,
    [VehAge]                            INT             NULL,
    [Vendor]                            VARCHAR (10)    NULL,
    [WIPCostCenterID]                   INT             NULL,
    [Year]                              SMALLINT        NULL,
    [MMR_MID]                           VARCHAR (35)    NULL,
    [DriverID]                          INT             NULL,
    [ClassBodyStyleID]                  DECIMAL (10)    NULL,
    [LicenseNumber]                     VARCHAR (50)    NULL,
    [TitleLocation]                     VARCHAR (50)    NULL,
    [FrontLineID]                       INT             NULL,
    [CurrentLot]                        INT             NULL,
    [CurrentDivision]                   INT             NULL,
    [BuyersFee]                         DECIMAL (15, 4) NULL,
    [CurrentReconCost]                  DECIMAL (15, 4) NULL,
    [AccountingInventoryAdjustments]    DECIMAL (15, 4) NULL,
    [ReconPartials]                     DECIMAL (15, 4) NULL,
    [AgePartials]                       DECIMAL (15, 4) NULL,
    [MarginAdjustment]                  DECIMAL (15, 4) NULL,
    [TrueTotalCost]                     DECIMAL (15, 4) NULL,
    [Margin]                            DECIMAL (15, 4) NULL,
    [SalesPrice]                        DECIMAL (15, 4) NULL,
    [VendorID]                          INT             NULL,
    [NadaVic]                           VARCHAR (50)    NULL,
    [QualityControlApproved]            VARCHAR (10)    NULL,
    [Trim]                              VARCHAR (50)    NULL,
    [AcquisitionCost]                   DECIMAL (15, 4) NULL,
    [RepoAuctionSaleDate]               DATETIME        NULL,
    [MMRRepoSaleAuctionAveragePrice]    DECIMAL (10, 2) NULL,
    [MMRRepoSaleAuctionCleanPrice]      DECIMAL (10, 2) NULL,
    [MMRRepoSaleRetailAveragePrice]     DECIMAL (10, 2) NULL,
    [MMRRepoSaleRetailCleanPrice]       DECIMAL (10, 2) NULL,
    [Ranking]                           SMALLINT        NULL,
    [SellerCd]                          BIGINT          NULL,
    [TotalWriteDownsRepHst]             DECIMAL (15, 4) NULL,
    [TotalWriteDownsPricing]            DECIMAL (15, 4) NULL,
    [ReconPartialsRepHst]               DECIMAL (15, 4) NULL,
    [ReconPartialsPricing]              DECIMAL (15, 4) NULL,
    [AgePartialsRepHst]                 DECIMAL (15, 4) NULL,
    [AgePartialsPricing]                DECIMAL (15, 4) NULL,
    [MarginAdjustmentRepHst]            DECIMAL (15, 4) NULL,
    [MarginAdjustmentPricing]           DECIMAL (15, 4) NULL,
    [AUCGUART]                          VARCHAR (10)    NULL,
    [PRIMEUNIT]                         VARCHAR (10)    NULL,
    [SELLCERT]                          VARCHAR (10)    NULL,
    [SPCCODE1]                          VARCHAR (10)    NULL,
    [SPCCODE3]                          VARCHAR (10)    NULL,
    [hasGPS]                            SMALLINT        NULL,
    [HasPhoto]                          SMALLINT        NULL,
    [AuctionType]                       VARCHAR (100)   NULL,
    [StockPurchaseOrderNumber]          VARCHAR (20)    NULL,
    [VehicleTierKey]                    VARCHAR (20)    NULL,
    [VehicleTierDisplayName]            VARCHAR (250)   NULL,
    [RowLoadedDateTime]                 DATETIME2 (7)   CONSTRAINT [DF_tblStock_RowLoadedDateTime] DEFAULT (getdate()) NULL,
    [RowUpdatedDateTime]                DATETIME2 (7)   NULL,
    CONSTRAINT [PK_tblStock] PRIMARY KEY CLUSTERED ([StockNumber] ASC) WITH (FILLFACTOR = 90)
);

