CREATE TABLE [dbo].[vEvaluateAdesa] (
    [pkAdesaPreSaleID]       INT            IDENTITY (1, 1) NOT NULL,
    [SaleDate]               NVARCHAR (MAX) NULL,
    [SaleType]               NVARCHAR (MAX) NULL,
    [OwnerID]                INT            NULL,
    [ConsignorType]          NVARCHAR (MAX) NULL,
    [Consignor]              NVARCHAR (MAX) NULL,
    [Location]               NVARCHAR (MAX) NULL,
    [Lot]                    NVARCHAR (MAX) NULL,
    [RunNumber]              INT            NULL,
    [Year]                   INT            NULL,
    [Make]                   NVARCHAR (MAX) NULL,
    [Model]                  NVARCHAR (MAX) NULL,
    [Body]                   NVARCHAR (MAX) NULL,
    [Series]                 NVARCHAR (MAX) NULL,
    [Engine]                 NVARCHAR (MAX) NULL,
    [Color]                  NVARCHAR (MAX) NULL,
    [Odometer]               INT            NULL,
    [OdometerType]           NVARCHAR (MAX) NULL,
    [VIN]                    NVARCHAR (MAX) NULL,
    [OpenSale]               NVARCHAR (MAX) NULL,
    [Transmission]           NVARCHAR (MAX) NULL,
    [Options]                NVARCHAR (MAX) NULL,
    [Announcement]           NVARCHAR (MAX) NULL,
    [RowLoadTimeStamp]       DATETIME       NULL,
    [RowUpDateTimeStamp]     DATETIME       NULL,
    [OpenLaneVehicleID]      INT            NULL,
    [Status]                 NVARCHAR (MAX) NULL,
    [Displacement]           NVARCHAR (MAX) NULL,
    [Cylinders]              INT            NULL,
    [DriveTrain]             NVARCHAR (MAX) NULL,
    [ChromeStyleID]          BIGINT         NULL,
    [InteriorColor]          NVARCHAR (MAX) NULL,
    [VehicleType]            NVARCHAR (MAX) NULL,
    [State]                  NVARCHAR (MAX) NULL,
    [ZipCode]                NVARCHAR (MAX) NULL,
    [CurrentHighBid]         BIGINT         NULL,
    [BINPrice]               BIGINT         NULL,
    [AuctionEndDateTime]     NVARCHAR (MAX) NULL,
    [TotalDamages]           INT            NULL,
    [VehicleDetailURL]       NVARCHAR (MAX) NULL,
    [ImageViewerURL]         NVARCHAR (MAX) NULL,
    [DealerCodes]            INT            NULL,
    [ImageURL]               NVARCHAR (MAX) NULL,
    [Lane]                   NVARCHAR (MAX) NULL,
    [IsRunListVehicle]       NVARCHAR (MAX) NULL,
    [IsLiveBlockVehicle]     NVARCHAR (MAX) NULL,
    [IsDealerBlockVehicle]   NVARCHAR (MAX) NULL,
    [AssetType]              NVARCHAR (MAX) NULL,
    [EqualsReserve]          NVARCHAR (MAX) NULL,
    [VehicleListingCategory] NVARCHAR (MAX) NULL,
    [VehicleGrade]           NVARCHAR (MAX) NULL,
    [ProcessingAuctionOrgID] INT            NULL,
    [IsAutograde]            NVARCHAR (MAX) NULL,
    [Comment]                NVARCHAR (MAX) NULL,
    [ChromeYear]             INT            NULL,
    [ChromeMake]             NVARCHAR (MAX) NULL,
    [ChromeModel]            NVARCHAR (MAX) NULL,
    [ChromeSeries]           NVARCHAR (MAX) NULL,
    [TitleState]             NVARCHAR (MAX) NULL,
    [Tires]                  NVARCHAR (MAX) NULL,
    [InspectionDate]         NVARCHAR (MAX) NULL,
    [InspectionCompany]      NVARCHAR (MAX) NULL,
    [InspectionComments]     NVARCHAR (MAX) NULL,
    [PriorPaint]             NVARCHAR (MAX) NULL,
    [Reserved1]              NVARCHAR (MAX) NULL,
    [Reserved2]              NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_dbo.vEvaluateAdesa] PRIMARY KEY CLUSTERED ([pkAdesaPreSaleID] ASC) WITH (FILLFACTOR = 90)
);

