CREATE TABLE [postsale].[tblManheimFeedStage] (
    [ManheimFeedStageSetID]                                             UNIQUEIDENTIFIER NOT NULL,
    [ListingID]                                                         VARCHAR (36)     NOT NULL,
    [CreatedOn]                                                         VARCHAR (40)     NULL,
    [ManheimFeedPurchaseDate]                                           VARCHAR (40)     NULL,
    [Channel]                                                           VARCHAR (10)     NULL,
    [ManheimFeedVIN]                                                    VARCHAR (17)     NULL,
    [ManheimFeedStatus]                                                 TINYINT          NULL,
    [UniqueID]                                                          VARCHAR (36)     NOT NULL,
    [ManheimFeedListingPurchaseDate]                                    VARCHAR (40)     NULL,
    [BlockTimestamp]                                                    VARCHAR (40)     NULL,
    [PurchaseOfferExists]                                               VARCHAR (20)     NULL,
    [PurchasePrice]                                                     MONEY            NULL,
    [Currency]                                                          VARCHAR (5)      NULL,
    [VehicleStatus]                                                     VARCHAR (64)     NULL,
    [PurchaseApplication]                                               VARCHAR (40)     NULL,
    [PurchaseMethod]                                                    VARCHAR (40)     NULL,
    [ManheimFeedListingConsignmentWorkOrderNumber]                      INT              NULL,
    [StartDate]                                                         VARCHAR (40)     NULL,
    [EndDate]                                                           VARCHAR (40)     NULL,
    [RegistrationDate]                                                  VARCHAR (40)     NULL,
    [OfferingApplication]                                               VARCHAR (40)     NULL,
    [OfferMethod]                                                       VARCHAR (20)     NULL,
    [SaleType]                                                          VARCHAR (13)     NULL,
    [AsIs]                                                              VARCHAR (20)     NULL,
    [Salvage]                                                           VARCHAR (20)     NULL,
    [ConsignorCode]                                                     VARCHAR (10)     NULL,
    [BidRestriction]                                                    VARCHAR (13)     NULL,
    [OfferingStatus]                                                    VARCHAR (16)     NULL,
    [OfferingStatusReason]                                              VARCHAR (96)     NULL,
    [Disclosures]                                                       NVARCHAR (MAX)   NULL,
    [ManheimFeedListingBuyerDealerNumber]                               VARCHAR (24)     NULL,
    [ManheimFeedListingBuyerDealerName]                                 VARCHAR (200)    NULL,
    [BidderBadge]                                                       VARCHAR (10)     NULL,
    [ManheimFeedListingBuyerHref]                                       VARCHAR (1000)   NULL,
    [ManheimFeedListingInvoiceHref]                                     VARCHAR (1000)   NULL,
    [ReceivedOn]                                                        VARCHAR (40)     NULL,
    [UpdatedOn]                                                         VARCHAR (40)     NULL,
    [ManheimFeedListingTitleStatus]                                     VARCHAR (20)     NULL,
    [TitleNotRequired]                                                  VARCHAR (20)     NULL,
    [ManheimFeedListingTitleVIN]                                        VARCHAR (17)     NULL,
    [ManheimFeedListingTitleYear]                                       SMALLINT         NULL,
    [ManheimFeedListingTitleMake]                                       VARCHAR (50)     NULL,
    [ManheimFeedListingTitleModel]                                      VARCHAR (100)    NULL,
    [BodyStyle]                                                         VARCHAR (16)     NULL,
    [ManheimFeedListingTitleHref]                                       VARCHAR (1000)   NULL,
    [StatusTimestamp]                                                   VARCHAR (40)     NULL,
    [ManheimFeedListingPostSaleInspectionStatus]                        VARCHAR (20)     NULL,
    [StatusReason]                                                      VARCHAR (96)     NULL,
    [InspectionType]                                                    VARCHAR (32)     NULL,
    [LegacyPSICode]                                                     VARCHAR (32)     NULL,
    [LegacyDay14Flag]                                                   VARCHAR (20)     NULL,
    [ManheimFeedListingPostSaleInspectionHref]                          VARCHAR (1000)   NULL,
    [Count]                                                             INT              NULL,
    [ManheimFeedListingCommentsHref]                                    VARCHAR (1000)   NULL,
    [ManheimFeedListingConsignmentUnitVIN]                              VARCHAR (17)     NULL,
    [ManheimFeedListingConsignmentUnitModelYear]                        SMALLINT         NULL,
    [ManheimFeedListingConsignmentUnitMake]                             VARCHAR (50)     NULL,
    [ManheimFeedListingConsignmentUnitModel]                            VARCHAR (100)    NULL,
    [Trim]                                                              VARCHAR (65)     NULL,
    [Body]                                                              VARCHAR (16)     NULL,
    [EngineDescription]                                                 VARCHAR (64)     NULL,
    [OdometerReading]                                                   INT              NULL,
    [OdometerUnits]                                                     VARCHAR (20)     NULL,
    [VehicleType]                                                       VARCHAR (48)     NULL,
    [InteriorColor]                                                     VARCHAR (15)     NULL,
    [ExteriorColor]                                                     VARCHAR (15)     NULL,
    [ManheimFeedListingConsignmentSellerDealerNumber]                   VARCHAR (24)     NULL,
    [ManheimFeedListingConsignmentSellerDealerName]                     VARCHAR (200)    NULL,
    [ManheimFeedListingOfferingOperatingLocationLocationName]           VARCHAR (80)     NULL,
    [ManheimFeedListingOfferingOperatingLocationLocationCode]           VARCHAR (24)     NULL,
    [ManheimFeedListingOfferingOperatingLocationHref]                   VARCHAR (1000)   NULL,
    [SaleYear]                                                          SMALLINT         NULL,
    [SaleNumber]                                                        TINYINT          NULL,
    [LaneNumber]                                                        TINYINT          NULL,
    [RunNumber]                                                         SMALLINT         NULL,
    [RepNumber]                                                         VARCHAR (480)    NULL,
    [RepName]                                                           VARCHAR (96)     NULL,
    [ManheimFeedListingBuyerRepHref]                                    VARCHAR (1000)   NULL,
    [Reading]                                                           INT              NULL,
    [Units]                                                             VARCHAR (20)     NULL,
    [ManheimFeedListingTitleOperatingLocationLocationName]              VARCHAR (80)     NULL,
    [ManheimFeedListingTitleOperatingLocationLocationCode]              VARCHAR (24)     NULL,
    [ManheimFeedListingTitleOperatingLocationHref]                      VARCHAR (1000)   NULL,
    [ManheimFeedListingPostSaleInspectionOperatingLocationLocationName] VARCHAR (80)     NULL,
    [ManheimFeedListingPostSaleInspectionOperatingLocationLocationCode] VARCHAR (24)     NULL,
    [ManheimFeedListingPostSaleInspectionOperatingLocationHref]         VARCHAR (1000)   NULL,
    [ManheimFeedListingPostSaleInspectionConsignmentWorkOrderNumber]    INT              NULL,
    [Offsite]                                                           VARCHAR (20)     NULL,
    [ManheimFeedListingConsignmentUnitPhysicalLocationLocationName]     VARCHAR (80)     NULL,
    [ManheimFeedListingConsignmentUnitPhysicalLocationLocationCode]     VARCHAR (24)     NULL,
    [ManheimFeedListingConsignmentUnitPhysicalLocationHref]             VARCHAR (1000)   NULL,
    [ManheimFeedListingPostSaleInspectionConsignmentUnitVIN]            VARCHAR (17)     NULL,
    [ManheimFeedListingPostSaleInspectionConsignmentUnitModelYear]      SMALLINT         NULL,
    [ManheimFeedListingPostSaleInspectionConsignmentUnitMake]           VARCHAR (50)     NULL,
    [ManheimFeedListingPostSaleInspectionConsignmentUnitModel]          VARCHAR (100)    NULL,
    [Address1]                                                          VARCHAR (96)     NULL,
    [City]                                                              VARCHAR (40)     NULL,
    [StateProvinceRegion]                                               VARCHAR (10)     NULL,
    [Country]                                                           VARCHAR (25)     NULL,
    [PostalCode]                                                        VARCHAR (24)     NULL,
    [ManheimFeedID]                                                     UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingID]                                              UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingConsignmentID]                                   UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingConsignmentID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingOfferingID]                                      UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingOfferingID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingBuyerID]                                         UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingBuyerID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingInvoiceID]                                       UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingInvoiceID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingTitleID]                                         UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingTitleID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingPostSaleInspectionID]                            UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingPostSaleInspectionID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingCommentsID]                                      UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingCommentsID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingConsignmentUnitID]                               UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingConsignmentUnitID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingConsignmentSellerID]                             UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingConsignmentSellerID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingOfferingOperatingLocationID]                     UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingOfferingOperatingLocationID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingOfferingSaleKeyID]                               UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingOfferingSaleKeyID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingBuyerRepID]                                      UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingBuyerRepID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingTitleOdometerID]                                 UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingTitleOdometerID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingTitleOperatingLocationID]                        UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingTitleOperatingLocationID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingPostSaleInspectionOperatingLocationID]           UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingPostSaleInspectionOperatingLocationID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingPostSaleInspectionConsignmentID]                 UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingPostSaleInspectionConsignmentID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingConsignmentUnitPhysicalLocationID]               UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingConsignmentUnitPhysicalLocationID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingPostSaleInspectionConsignmentUnitID]             UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingPostSaleInspectionConsignmentUnitID] DEFAULT (newid()) NOT NULL,
    [ManheimFeedListingConsignmentUnitPhysicalLocationAddressID]        UNIQUEIDENTIFIER CONSTRAINT [DF_tblManheimFeedStage_ManheimFeedListingConsignmentUnitPhysicalLocationAddressID] DEFAULT (newid()) NOT NULL,
    [RowLoadedDateTime]                                                 DATETIME2 (3)    CONSTRAINT [DF_tblManheimFeedStage_RowLoadedDateTime] DEFAULT (sysutcdatetime()) NOT NULL
);

