CREATE TABLE [presale].[tblManheimConditionReport] (
    [ManheimConditionReportID]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [RowLoadedDateTime]             DATETIME2 (3)  CONSTRAINT [DF_tblManheimConditionReportID_RowLoadedDateTime] DEFAULT (sysdatetime()) NOT NULL,
    [RowUpdatedDateTime]            DATETIME2 (3)  NULL,
    [VIN]                           VARCHAR (20)   NULL,
    [ConditionGradeNumDecimal]      NUMERIC (3, 1) NULL,
    [WorkOrderNumber]               VARCHAR (200)  NULL,
    [SBLU]                          VARCHAR (100)  NULL,
    [SellerUnivNumber]              VARCHAR (200)  NULL,
    [LeaseAccountNumber]            VARCHAR (300)  NULL,
    [SaleYear]                      VARCHAR (100)  NULL,
    [SaleNumber]                    VARCHAR (100)  NULL,
    [LaneNumber]                    VARCHAR (100)  NULL,
    [RunNumber]                     VARCHAR (100)  NULL,
    [SellerName]                    VARCHAR (300)  NULL,
    [Announcement]                  VARCHAR (1000) NULL,
    [ReceivedDate]                  VARCHAR (200)  NULL,
    [TitledState]                   VARCHAR (100)  NULL,
    [TitledReceivedDate]            VARCHAR (200)  NULL,
    [InserviceDate]                 VARCHAR (200)  NULL,
    [GroupCode]                     VARCHAR (200)  NULL,
    [BusinessUnit]                  VARCHAR (200)  NULL,
    [PreReconGrade]                 VARCHAR (200)  NULL,
    [Year]                          VARCHAR (100)  NULL,
    [Make]                          VARCHAR (200)  NULL,
    [Model]                         VARCHAR (200)  NULL,
    [Body]                          VARCHAR (100)  NULL,
    [SubSeries]                     VARCHAR (100)  NULL,
    [TopType]                       VARCHAR (200)  NULL,
    [ExteriorColor]                 VARCHAR (200)  NULL,
    [InteriorColor]                 VARCHAR (100)  NULL,
    [Transmission]                  VARCHAR (100)  NULL,
    [SideAirbags]                   VARCHAR (100)  NULL,
    [PostReconGrade]                VARCHAR (100)  NULL,
    [Author]                        VARCHAR (50)   NULL,
    [WrittenDate]                   VARCHAR (50)   NULL,
    [TireConditionCode]             VARCHAR (100)  NULL,
    [WheelType]                     VARCHAR (300)  NULL,
    [DrivableCode]                  VARCHAR (200)  NULL,
    [DamagesChargeable]             VARCHAR (MAX)  NULL,
    [TireInformation]               VARCHAR (MAX)  NULL,
    [Successful]                    VARCHAR (100)  NULL,
    [ThirdPartyECR]                 VARCHAR (200)  NULL,
    [MechanicalData]                VARCHAR (1000) NULL,
    [OptionsData]                   VARCHAR (7999) NULL,
    [InteriorData]                  VARCHAR (500)  NULL,
    [ShowWarranty]                  VARCHAR (100)  NULL,
    [ExteriorColorCode]             VARCHAR (100)  NULL,
    [InteriorColorCode]             VARCHAR (100)  NULL,
    [AnnouncedCondition]            VARCHAR (1000) NULL,
    [InternetRemarks]               VARCHAR (500)  NULL,
    [AdditionalDamageRemarks]       VARCHAR (1000) NULL,
    [Disclosures]                   VARCHAR (500)  NULL,
    [CommentsForConsignor]          VARCHAR (1000) NULL,
    [EngineStart]                   VARCHAR (200)  NULL,
    [FrameDamage]                   VARCHAR (200)  NULL,
    [AuctionId]                     VARCHAR (100)  NULL,
    [AuctionName]                   VARCHAR (200)  NULL,
    [AuctionAddress]                VARCHAR (300)  NULL,
    [AuctionCity]                   VARCHAR (200)  NULL,
    [AuctionState]                  VARCHAR (1000) NULL,
    [AuctionZip]                    VARCHAR (100)  NULL,
    [AuctionPhone]                  VARCHAR (100)  NULL,
    [Miles]                         VARCHAR (200)  NULL,
    [Digits]                        VARCHAR (100)  NULL,
    [Operable]                      VARCHAR (100)  NULL,
    [Digital]                       VARCHAR (100)  NULL,
    [BasicWarrantyDescription]      VARCHAR (500)  NULL,
    [BasicWarrantyValid]            VARCHAR (100)  NULL,
    [BasicWarrantyUnlimited]        VARCHAR (100)  NULL,
    [PowertrainWarrantyDescription] VARCHAR (500)  NULL,
    [PowertrainWarrantyValid]       VARCHAR (100)  NULL,
    [PowertrainWarrantyUnlimited]   VARCHAR (100)  NULL,
    CONSTRAINT [PK_tblManheimConditionReport] PRIMARY KEY CLUSTERED ([ManheimConditionReportID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [idx_tblManheimConditionReport_ConditionGradeNumDecimal]
    ON [presale].[tblManheimConditionReport]([ConditionGradeNumDecimal] ASC)
    INCLUDE([VIN]) WITH (FILLFACTOR = 90);

