CREATE TYPE [presale].[typAuctionEdgeFeed] AS TABLE (
    [VIN]                             VARCHAR (17)   NULL,
    [AuctionID]                       VARCHAR (10)   NULL,
    [SaleDate]                        DATE           NULL,
    [IsDeleted]                       TINYINT        NOT NULL,
    [UVC]                             VARCHAR (20)   NULL,
    [URL]                             VARCHAR (200)  NULL,
    [ExternalStockNumber]             VARCHAR (20)   NULL,
    [BidOnline]                       CHAR (1)       NULL,
    [CreatedAtDateTimeUTC]            DATETIME2 (7)  NULL,
    [UpdatedAtDateTimeUTC]            DATETIME2 (7)  NULL,
    [OdometerReading]                 INT            NULL,
    [TitleState]                      VARCHAR (200)  NULL,
    [BookValue]                       INT            NULL,
    [CheckInAtDateTimeUTC]            DATETIME2 (7)  NULL,
    [GlobalConsignorKey]              SMALLINT       NULL,
    [GlobalConsignorName]             VARCHAR (200)  NULL,
    [OdometerStatus]                  VARCHAR (50)   NULL,
    [BuyNowExpiresAtDateTimeUTC]      DATETIME2 (7)  NULL,
    [BuyNowPrice]                     INT            NULL,
    [OdometerComment]                 VARCHAR (200)  NULL,
    [MSRP]                            INT            NULL,
    [AuctionSaleDayID]                VARCHAR (200)  NULL,
    [ConsignmentDateTimeUTC]          DATETIME2 (7)  NULL,
    [RunNumber]                       VARCHAR (200)  NULL,
    [LaneName]                        VARCHAR (200)  NULL,
    [LaneTitle]                       VARCHAR (200)  NULL,
    [PhysicalLaneName]                VARCHAR (200)  NULL,
    [Announcements]                   VARCHAR (8000) NULL,
    [Certifications]                  VARCHAR (8000) NULL,
    [Year]                            VARCHAR (200)  NULL,
    [Make]                            VARCHAR (200)  NULL,
    [Model]                           VARCHAR (200)  NULL,
    [Series]                          VARCHAR (200)  NULL,
    [MakeModelSeries]                 VARCHAR (200)  NULL,
    [BodyStyle]                       VARCHAR (200)  NULL,
    [OriginalBodyStyle]               VARCHAR (200)  NULL,
    [ExteriorColor]                   VARCHAR (200)  NULL,
    [InteriorColor]                   VARCHAR (200)  NULL,
    [InteriorMaterial]                VARCHAR (200)  NULL,
    [EngineSize]                      VARCHAR (200)  NULL,
    [Cylinders]                       VARCHAR (200)  NULL,
    [DriveType]                       VARCHAR (200)  NULL,
    [FuelType]                        VARCHAR (200)  NULL,
    [TransmissionType]                VARCHAR (200)  NULL,
    [DoorConfiguration]               VARCHAR (200)  NULL,
    [OptionJSON]                      VARCHAR (8000) NULL,
    [SaleLightsJSON]                  VARCHAR (8000) NULL,
    [ImageURLJSON]                    VARCHAR (MAX)  NULL,
    [TireJSON]                        VARCHAR (8000) NULL,
    [ConditionReportItemJSON]         VARCHAR (MAX)  NULL,
    [ConditionReportCreatedAtDateUTC] DATE           NULL,
    [Author]                          VARCHAR (200)  NULL,
    [Grade]                           VARCHAR (200)  NULL,
    [FrameDamage]                     CHAR (1)       NULL,
    [Drivable]                        CHAR (1)       NULL,
    [OriginalPaint]                   CHAR (1)       NULL,
    [AutoGrade]                       DECIMAL (5, 1) NULL,
    UNIQUE NONCLUSTERED ([VIN] ASC, [AuctionID] ASC, [SaleDate] ASC));

