CREATE TABLE [Audit].[tblAccuCheck] (
    [AccuCheckID]                   INT           NOT NULL,
    [RowLoadedDateTime]             DATETIME2 (3) NOT NULL,
    [RowUpdatedDateTime]            DATETIME2 (3) NOT NULL,
    [VehMixedVID]                   VARCHAR (17)  NOT NULL,
    [VehMixedIDType]                VARCHAR (200) NOT NULL,
    [VehMixedCount]                 INT           NOT NULL,
    [VehMixedLastState]             VARCHAR (100) NOT NULL,
    [VehMixedLastTitle]             VARCHAR (200) NOT NULL,
    [VehMixedLastDate]              DATETIME2 (3) NULL,
    [VehMixedLastOdometer]          INT           NULL,
    [VehMixedRollback]              TINYINT       NOT NULL,
    [VehMixedSalvage]               TINYINT       NOT NULL,
    [VehMixedFailedEmission]        TINYINT       NOT NULL,
    [VehMixedDamage]                TINYINT       NOT NULL,
    [VehMixedLemon]                 TINYINT       NOT NULL,
    [VehMixedOdometerProblem]       TINYINT       NOT NULL,
    [VehMixedTheft]                 TINYINT       NOT NULL,
    [VehMixedTheftRecovered]        TINYINT       NOT NULL,
    [VehMixedWaterDamage]           TINYINT       NOT NULL,
    [VehMixedAbandoned]             TINYINT       NOT NULL,
    [VehMixedJunk]                  TINYINT       NOT NULL,
    [VehMixedRecycled]              TINYINT       NOT NULL,
    [VehMixedGreyMarket]            TINYINT       NOT NULL,
    [VehMixedRebuilt]               TINYINT       NOT NULL,
    [VehMixedCanadianRegistration]  TINYINT       NOT NULL,
    [VehMixedTitleRegStorm]         TINYINT       NOT NULL,
    [VehMixedRentalFleet]           TINYINT       NOT NULL,
    [VehMixedHailDamage]            TINYINT       NOT NULL,
    [VehMixedNHTSACrashTestVehicle] TINYINT       NOT NULL,
    [VehMixedFireDamage]            TINYINT       NOT NULL,
    [VehMixedFrameDamage]           TINYINT       NOT NULL,
    [VehMixedInsuranceLoss]         TINYINT       NOT NULL,
    [VINDecodeVIN]                  VARCHAR (17)  NOT NULL,
    [VINDecodeYear]                 INT           NOT NULL,
    [VINDecodeMFG]                  VARCHAR (200) NULL,
    [VINDecodeMFGCode]              INT           NULL,
    [VINDecodeModel]                VARCHAR (500) NULL,
    [VINDecodeSeriesCode]           INT           NULL,
    [VINDecodeBody]                 VARCHAR (200) NOT NULL,
    [VINDecodeEngine]               VARCHAR (200) NOT NULL,
    [VINDecodeCountry]              VARCHAR (200) NOT NULL,
    [VINDecodeResultCode]           INT           NULL,
    [VINDecodeResultMessage]        VARCHAR (200) NULL,
    [VINDecodeClass]                VARCHAR (200) NULL,
    [ScoreOwnerCount]               INT           NULL,
    [ScoreAge]                      INT           NULL,
    [ScoreScore]                    INT           NULL,
    [ScoreCompareScoreRangeHigh]    INT           NULL,
    [ScoreCompareScoreRangeLow]     INT           NULL,
    [ScorePosScoreFactor1]          VARCHAR (200) NULL,
    [ScorePosScoreFactor2]          VARCHAR (200) NULL,
    [ScoreNegScoreFactor1]          VARCHAR (200) NULL,
    [ScoreNegScoreFactor2]          VARCHAR (200) NULL,
    [ScoreNegScoreFactor3]          VARCHAR (200) NULL,
    [HistoryCount]                  INT           NOT NULL,
    [HistoryOdometer]               TINYINT       NOT NULL,
    [HistoryRollback]               TINYINT       NOT NULL,
    [HistoryMixedOdometer]          TINYINT       NULL,
    [HistoryAssured]                TINYINT       NULL,
    [HistoryBBP]                    INT           NULL,
    [HistoryLastOdometer]           INT           NULL,
    [HistoryAccidentCount]          INT           NOT NULL,
    [HistoryRecallCount]            INT           NOT NULL,
    [HistoryConditionRPT]           TINYINT       NULL,
    [HistoryRecallDataAvailable]    TINYINT       NOT NULL,
    [HistoryEstimatedAverageMiles]  INT           NULL,
    [ValidFromDate]                 DATETIME2 (7) NOT NULL,
    [ValidToDate]                   DATETIME2 (7) NOT NULL
);


GO
CREATE CLUSTERED INDEX [ix_tblAccuCheck]
    ON [Audit].[tblAccuCheck]([ValidToDate] ASC, [ValidFromDate] ASC) WITH (DATA_COMPRESSION = PAGE);

